name: 'Get Versions'
description: 'Gets all version information needed for Patchright .NET builds'

outputs:
  playwright_version:
    description: 'Latest Playwright .NET version (e.g., 1.57.0)'
    value: ${{ steps.playwright.outputs.version }}
  playwright_major_minor:
    description: 'Playwright major.minor version (e.g., 1.57)'
    value: ${{ steps.playwright.outputs.major_minor }}
  patchright_version:
    description: 'Latest Patchright .NET release version'
    value: ${{ steps.patchright.outputs.version }}
  driver_version:
    description: 'Latest compatible Patchright driver version'
    value: ${{ steps.driver.outputs.version }}
  driver_available:
    description: 'Whether a compatible driver was found (true/false)'
    value: ${{ steps.driver.outputs.available }}
  nuget_version:
    description: 'Latest Patchright .NET version published on NuGet.org'
    value: ${{ steps.nuget.outputs.version }}
  nuget_versions:
    description: 'All Patchright .NET versions published on NuGet.org (JSON array)'
    value: ${{ steps.nuget.outputs.versions }}

runs:
  using: 'composite'
  steps:
    - name: Get latest Playwright .NET version
      id: playwright
      shell: bash
      run: |
        echo "Fetching latest Playwright .NET release..."
        
        # Retry logic with exponential backoff
        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          if [ $RETRY_COUNT -gt 0 ]; then
            WAIT_TIME=$((2 ** RETRY_COUNT))
            echo "Retry $RETRY_COUNT/$MAX_RETRIES after ${WAIT_TIME}s..."
            sleep $WAIT_TIME
          fi
          
          RESPONSE=$(curl -s -w "\n%{http_code}" https://api.github.com/repos/microsoft/playwright-dotnet/releases/latest)
          HTTP_CODE=$(echo "$RESPONSE" | tail -1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ]; then
            # Validate JSON and check for tag_name
            if echo "$BODY" | jq -e '.tag_name' > /dev/null 2>&1; then
              TAG=$(echo "$BODY" | jq -r '.tag_name')
              VERSION="${TAG#v}"
              MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
              
              echo "Latest Playwright .NET: $VERSION (major.minor: $MAJOR_MINOR)"
              echo "version=$VERSION" >> $GITHUB_OUTPUT
              echo "major_minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT
              SUCCESS=true
            else
              echo "ERROR: Invalid JSON response or missing tag_name"
              echo "Response body (first 500 chars):"
              echo "$BODY" | head -c 500
              RETRY_COUNT=$((RETRY_COUNT + 1))
            fi
          else
            echo "ERROR: GitHub API returned status $HTTP_CODE"
            echo "Response body (first 500 chars):"
            echo "$BODY" | head -c 500
            RETRY_COUNT=$((RETRY_COUNT + 1))
          fi
        done
        
        if [ "$SUCCESS" = false ]; then
          echo "FATAL: Failed to fetch Playwright version after $MAX_RETRIES retries"
          exit 1
        fi
    
    - name: Get latest Patchright .NET version
      id: patchright
      shell: bash
      run: |
        echo "Fetching latest Patchright .NET release..."
        
        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          if [ $RETRY_COUNT -gt 0 ]; then
            WAIT_TIME=$((2 ** RETRY_COUNT))
            echo "Retry $RETRY_COUNT/$MAX_RETRIES after ${WAIT_TIME}s..."
            sleep $WAIT_TIME
          fi
          
          RESPONSE=$(curl -s -w "\n%{http_code}" https://api.github.com/repos/DevEnterpriseSoftware/patchright-dotnet/releases/latest)
          HTTP_CODE=$(echo "$RESPONSE" | tail -1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ]; then
            TAG=$(echo "$BODY" | jq -r '.tag_name // "v0.0.0"')
            VERSION="${TAG#v}"
            echo "Latest Patchright .NET: $VERSION"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            SUCCESS=true
          elif [ "$HTTP_CODE" = "404" ]; then
            echo "No releases found for Patchright .NET (404)"
            VERSION="0.0.0"
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            SUCCESS=true
          else
            echo "ERROR: GitHub API returned status $HTTP_CODE"
            echo "Response body (first 500 chars):"
            echo "$BODY" | head -c 500
            RETRY_COUNT=$((RETRY_COUNT + 1))
          fi
        done
        
        if [ "$SUCCESS" = false ]; then
          echo "FATAL: Failed to fetch Patchright version after $MAX_RETRIES retries"
          exit 1
        fi
    
    - name: Get latest compatible Patchright driver version
      id: driver
      shell: bash
      run: |
        echo "Fetching all Patchright driver releases..."
        PLAYWRIGHT_MAJOR_MINOR="${{ steps.playwright.outputs.major_minor }}"
        echo "Looking for driver versions matching major.minor: $PLAYWRIGHT_MAJOR_MINOR"
        
        # Validate we have a major.minor version
        if [ -z "$PLAYWRIGHT_MAJOR_MINOR" ] || [ "$PLAYWRIGHT_MAJOR_MINOR" = "null" ]; then
          echo "ERROR: No valid Playwright major.minor version available"
          echo "version=" >> $GITHUB_OUTPUT
          echo "available=false" >> $GITHUB_OUTPUT
          exit 1
        fi
        
        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          if [ $RETRY_COUNT -gt 0 ]; then
            WAIT_TIME=$((2 ** RETRY_COUNT))
            echo "Retry $RETRY_COUNT/$MAX_RETRIES after ${WAIT_TIME}s..."
            sleep $WAIT_TIME
          fi
          
          RESPONSE=$(curl -s -w "\n%{http_code}" "https://api.github.com/repos/Kaliiiiiiiiii-Vinyzu/patchright/releases?per_page=10")
          HTTP_CODE=$(echo "$RESPONSE" | tail -1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ]; then
            # Validate it's a JSON array
            if echo "$BODY" | jq -e 'type == "array"' > /dev/null 2>&1; then
              MATCHING_VERSION=$(echo "$BODY" | jq -r '.[].tag_name' | \
                sed 's/^v//' | \
                grep "^${PLAYWRIGHT_MAJOR_MINOR}\." | \
                sort -V | \
                tail -1)
              
              if [ -n "$MATCHING_VERSION" ] && [ "$MATCHING_VERSION" != "" ]; then
                echo "Found compatible driver version: $MATCHING_VERSION"
                echo "version=$MATCHING_VERSION" >> $GITHUB_OUTPUT
                echo "available=true" >> $GITHUB_OUTPUT
                
                echo ""
                echo "All matching versions for $PLAYWRIGHT_MAJOR_MINOR:"
                echo "$BODY" | jq -r '.[].tag_name' | sed 's/^v//' | grep "^${PLAYWRIGHT_MAJOR_MINOR}\." | sort -V
              else
                echo "No driver version found matching major.minor $PLAYWRIGHT_MAJOR_MINOR"
                echo "Available driver versions:"
                echo "$BODY" | jq -r '.[].tag_name' | head -10
                echo "version=" >> $GITHUB_OUTPUT
                echo "available=false" >> $GITHUB_OUTPUT
              fi
              SUCCESS=true
            else
              echo "ERROR: Response is not a valid JSON array"
              echo "Response body (first 500 chars):"
              echo "$BODY" | head -c 500
              RETRY_COUNT=$((RETRY_COUNT + 1))
            fi
          else
            echo "ERROR: GitHub API returned status $HTTP_CODE"
            echo "Response body (first 500 chars):"
            echo "$BODY" | head -c 500
            RETRY_COUNT=$((RETRY_COUNT + 1))
          fi
        done
        
        if [ "$SUCCESS" = false ]; then
          echo "FATAL: Failed to fetch driver version after $MAX_RETRIES retries"
          exit 1
        fi
    
    - name: Get NuGet.org published versions
      id: nuget
      shell: bash
      run: |
        echo "Fetching Patchright .NET versions from NuGet.org..."
        
        MAX_RETRIES=3
        RETRY_COUNT=0
        SUCCESS=false
        
        while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$SUCCESS" = false ]; do
          if [ $RETRY_COUNT -gt 0 ]; then
            WAIT_TIME=$((2 ** RETRY_COUNT))
            echo "Retry $RETRY_COUNT/$MAX_RETRIES after ${WAIT_TIME}s..."
            sleep $WAIT_TIME
          fi
          
          RESPONSE=$(curl -s -w "\n%{http_code}" "https://api.nuget.org/v3-flatcontainer/patchright/index.json")
          HTTP_CODE=$(echo "$RESPONSE" | tail -1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          
          echo "HTTP Status: $HTTP_CODE"
          
          if [ "$HTTP_CODE" = "200" ]; then
            if echo "$BODY" | jq -e '.versions' > /dev/null 2>&1; then
              # Ensure all versions are strings in the JSON array to easily compare later
              VERSIONS=$(echo "$BODY" | jq -c '[.versions[] | tostring]')
              LATEST=$(echo "$BODY" | jq -r '.versions[-1] // ""')
              
              echo "Latest NuGet version: $LATEST"
              echo "version=$LATEST" >> $GITHUB_OUTPUT
              echo "versions=$VERSIONS" >> $GITHUB_OUTPUT
              SUCCESS=true
            else
              echo "ERROR: Invalid JSON or missing versions field"
              echo "Response body (first 500 chars):"
              echo "$BODY" | head -c 500
              RETRY_COUNT=$((RETRY_COUNT + 1))
            fi
          elif [ "$HTTP_CODE" = "404" ]; then
            echo "No Patchright .NET versions found on NuGet.org (404)"
            echo "version=" >> $GITHUB_OUTPUT
            echo "versions=[]" >> $GITHUB_OUTPUT
            SUCCESS=true
          else
            echo "ERROR: NuGet API returned status $HTTP_CODE"
            echo "Response body (first 500 chars):"
            echo "$BODY" | head -c 500
            RETRY_COUNT=$((RETRY_COUNT + 1))
          fi
        done
        
        if [ "$SUCCESS" = false ]; then
          echo "FATAL: Failed to fetch NuGet versions after $MAX_RETRIES retries"
          exit 1
        fi
