name: 'Get Versions'
description: 'Gets all version information needed for Patchright .NET builds'

outputs:
  playwright_version:
    description: 'Latest Playwright .NET version (e.g., 1.57.0)'
    value: ${{ steps.playwright.outputs.version }}
  playwright_major_minor:
    description: 'Playwright major.minor version (e.g., 1.57)'
    value: ${{ steps.playwright.outputs.major_minor }}
  patchright_version:
    description: 'Latest Patchright .NET release version'
    value: ${{ steps.patchright.outputs.version }}
  driver_version:
    description: 'Latest compatible Patchright driver version'
    value: ${{ steps.driver.outputs.version }}
  driver_available:
    description: 'Whether a compatible driver was found (true/false)'
    value: ${{ steps.driver.outputs.available }}

runs:
  using: 'composite'
  steps:
    - name: Get latest Playwright .NET version
      id: playwright
      shell: bash
      run: |
        echo "Fetching latest Playwright .NET release..."
        RESPONSE=$(curl -s https://api.github.com/repos/microsoft/playwright-dotnet/releases/latest)
        TAG=$(echo "$RESPONSE" | jq -r '.tag_name')
        VERSION="${TAG#v}"  # Remove 'v' prefix
        MAJOR_MINOR=$(echo "$VERSION" | cut -d. -f1,2)
        
        echo "Latest Playwright .NET: $VERSION (major.minor: $MAJOR_MINOR)"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "major_minor=$MAJOR_MINOR" >> $GITHUB_OUTPUT
    
    - name: Get latest Patchright .NET version
      id: patchright
      shell: bash
      run: |
        echo "Fetching latest Patchright .NET release..."
        RESPONSE=$(curl -s https://api.github.com/repos/DevEnterpriseSoftware/patchright-dotnet/releases/latest)
        
        # Handle case where no releases exist yet
        if echo "$RESPONSE" | jq -e '.message == "Not Found"' > /dev/null 2>&1; then
          echo "No releases found for Patchright .NET"
          VERSION="0.0.0"
        else
          TAG=$(echo "$RESPONSE" | jq -r '.tag_name // "v0.0.0"')
          VERSION="${TAG#v}"  # Remove 'v' prefix
        fi
        
        echo "Latest Patchright .NET: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Get latest compatible Patchright driver version
      id: driver
      shell: bash
      run: |
        echo "Fetching all Patchright driver releases..."
        PLAYWRIGHT_MAJOR_MINOR="${{ steps.playwright.outputs.major_minor }}"
        echo "Looking for driver versions matching major.minor: $PLAYWRIGHT_MAJOR_MINOR"
        
        # Fetch releases (up to 10)
        RESPONSE=$(curl -s "https://api.github.com/repos/Kaliiiiiiiiii-Vinyzu/patchright/releases?per_page=10")
        
        # Extract all version tags, remove 'v' prefix, filter by major.minor, sort by version, get highest
        MATCHING_VERSION=$(echo "$RESPONSE" | jq -r '.[].tag_name' | \
          sed 's/^v//' | \
          grep "^${PLAYWRIGHT_MAJOR_MINOR}\." | \
          sort -V | \
          tail -1)
        
        if [ -n "$MATCHING_VERSION" ] && [ "$MATCHING_VERSION" != "" ]; then
          echo "Found compatible driver version: $MATCHING_VERSION"
          echo "version=$MATCHING_VERSION" >> $GITHUB_OUTPUT
          echo "available=true" >> $GITHUB_OUTPUT
          
          # Show all matching versions for debugging
          echo ""
          echo "All matching versions for $PLAYWRIGHT_MAJOR_MINOR:"
          echo "$RESPONSE" | jq -r '.[].tag_name' | sed 's/^v//' | grep "^${PLAYWRIGHT_MAJOR_MINOR}\." | sort -V
        else
          echo "No driver version found matching major.minor $PLAYWRIGHT_MAJOR_MINOR"
          echo "Available driver versions:"
          echo "$RESPONSE" | jq -r '.[].tag_name' | head -10
          echo "version=" >> $GITHUB_OUTPUT
          echo "available=false" >> $GITHUB_OUTPUT
        fi
